apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*

build:
  local:
    push: false
  artifacts:
    - image: mhdbilal/jobpilot-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
    - image: mhdbilal/jobpilot-employer
      context: employer
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
    - image: mhdbilal/jobpilot-job
      context: job
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
    - image: mhdbilal/jobpilot-user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
    - image: mhdbilal/jobpilot-chat
      context: chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
        - src: 'src/**/*.ts'
          dest: .
