apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: mhdbilal/jobpilot-chat
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: chat-mongo
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: chat-clsip-srv
spec:
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3004
      targetPort: 3004