name: deploy-auth

on: 
 push:
   branches:
     - master
   paths:
     - 'auth/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Build Docker Image
       run: |
         cd auth
         docker build -t mhdbilal/jobpilot-auth .
     - name: Login to Docker Hub
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push Docker Image
       run: docker push mhdbilal/jobpilot-auth
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save 8d2b60e0-8538-434c-bb80-15c84f7652f5
     - run: kubectl rollout restart deployment auth-depl
