name: deploy-user

on: 
 push:
   branches:
     - master
   paths:
     - 'user/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Build Docker Image
       run: |
         cd user
         docker build -t mhdbilal/jobpilot-user .
     - name: Login to Docker Hub
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push Docker Image
       run: docker push mhdbilal/jobpilot-user
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save ff6be6c5-44f6-4ffc-9046-f51a82a7f20f
     - run: kubectl rollout restart deployment user-depl
