name: deploy-manifest

on: 
 push:
   branches:
     - master
   paths:
     - 'infra/**'
     
jobs: 
 build:
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout code
       uses: actions/checkout@v3
     - uses: digitalocean/action-doctl@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save 7c074672-961b-44c7-ba41-42477278456c
     - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
